# Generated by Django 4.2.3 on 2024-09-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_employee_name_alter_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
    ]
