# Generated by Django 4.2.3 on 2024-09-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_remove_employee_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Manager', 'Manager'), ('Locality Manager', 'LocalityManager'), ('Caller', 'Caller'), ('Visitor', 'Visitor'), ('Visitor and Caller', 'VisitorCaller')], default='user', max_length=100),
        ),
    ]
