# Generated by Django 4.2.3 on 2024-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_remove_employee_last_name_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Manager', 'Manager'), ('Locality Manager', 'LocalityManager'), ('Caller', 'Caller'), ('Visitor', 'Visitor'), ('Visitor and Caller', 'VisitorCaller')], max_length=100, null=True),
        ),
    ]
