# Generated by Django 4.2.3 on 2023-07-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0014_rename_location_latitude_project_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formatted_version', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
