# Generated by Django 4.2.3 on 2023-07-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0015_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('value', models.FloatField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='home_API.units'),
        ),
    ]
