# Generated by Django 4.2.3 on 2023-07-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0016_units_alter_unit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contactNumber',
            field=models.PositiveBigIntegerField(),
        ),
    ]
