# Generated by Django 4.2.3 on 2023-07-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0017_alter_project_contactnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formatted_version', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
