# Generated by Django 4.2.3 on 2023-07-31 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0018_governmentalarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='home_API.area'),
        ),
        migrations.AlterField(
            model_name='project',
            name='areaIn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='home_API.governmentalarea'),
        ),
    ]
