# Generated by Django 4.2.3 on 2023-07-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0019_alter_project_area_alter_project_areain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='areaIn',
            field=models.CharField(max_length=100),
        ),
    ]
