# Generated by Django 4.2.3 on 2023-07-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0015_area'),
        ('client_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchfilter',
            name='Area',
        ),
        migrations.AddField(
            model_name='searchfilter',
            name='Area',
            field=models.ManyToManyField(to='home_API.area'),
        ),
    ]
