# Generated by Django 4.2.3 on 2023-07-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_API', '0003_remove_searchfilter_units_searchfilter_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='massageNO',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='phoneNO',
            field=models.PositiveBigIntegerField(),
        ),
    ]
